#!/usr/bin/env node
/**
 * GoHighLevel MCP Server
 *
 * Exposes the full surface of the official @gohighlevel/api-client SDK as MCP tools.
 * Tools are auto-generated by src/codegen/generate.ts.
 *
 * Configure via env vars:
 *   GHL_PRIVATE_INTEGRATION_TOKEN  (required) — Private Integration Token from GHL
 *   GHL_DEFAULT_LOCATION_ID        (optional) — used as fallback when a tool needs locationId
 */
import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";
import { HighLevel } from "@gohighlevel/api-client";
import { generatedTools, type GeneratedTool } from "./tools.generated.js";

const TOKEN = process.env.GHL_PRIVATE_INTEGRATION_TOKEN;
const DEFAULT_LOCATION_ID = process.env.GHL_DEFAULT_LOCATION_ID;

if (!TOKEN) {
  console.error(
    "[ghl-mcp-server] GHL_PRIVATE_INTEGRATION_TOKEN env var is required."
  );
  process.exit(1);
}

// Instantiate the SDK once. The client is reused across every tool call.
const ghl = new HighLevel({
  privateIntegrationToken: TOKEN,
});

// Build a lookup so tool name -> spec is O(1).
const toolByName = new Map<string, GeneratedTool>();
for (const t of generatedTools) toolByName.set(t.name, t);

const server = new Server(
  {
    name: "ghl-mcp-server",
    version: "0.1.0",
  },
  {
    capabilities: {
      tools: {},
    },
  }
);

server.setRequestHandler(ListToolsRequestSchema, async () => {
  return {
    tools: generatedTools.map((t) => ({
      name: t.name,
      description: t.description,
      inputSchema: t.inputSchema,
    })),
  };
});

server.setRequestHandler(CallToolRequestSchema, async (req) => {
  const { name, arguments: args } = req.params;
  const spec = toolByName.get(name);
  if (!spec) {
    return {
      isError: true,
      content: [{ type: "text", text: `Unknown tool: ${name}` }],
    };
  }

  // Resolve the SDK service: ghl[serviceProperty]
  const service = (ghl as any)[spec.serviceProperty];
  if (!service || typeof service[spec.methodName] !== "function") {
    return {
      isError: true,
      content: [
        {
          type: "text",
          text: `Internal error: SDK has no ${spec.serviceProperty}.${spec.methodName}`,
        },
      ],
    };
  }

  // Build call arguments: every generated tool accepts { params?, requestBody? }
  const rawArgs = (args ?? {}) as Record<string, any>;
  const params: Record<string, any> = { ...(rawArgs.params ?? {}) };
  const requestBody = rawArgs.requestBody;

  // If the method expects a locationId and the caller did not provide one,
  // fall back to GHL_DEFAULT_LOCATION_ID.
  if (
    DEFAULT_LOCATION_ID &&
    paramExpectsLocationId(spec) &&
    !params.locationId
  ) {
    params.locationId = DEFAULT_LOCATION_ID;
  }

  try {
    let result: unknown;
    if (spec.hasRequestBody) {
      result = await service[spec.methodName](params, requestBody);
    } else {
      result = await service[spec.methodName](params);
    }
    return {
      content: [
        {
          type: "text",
          text:
            typeof result === "string"
              ? result
              : JSON.stringify(result, null, 2),
        },
      ],
    };
  } catch (err: any) {
    // Surface GHL/Axios error details when present.
    const status = err?.statusCode ?? err?.response?.status;
    const data = err?.response?.data ?? err?.response;
    const message = err?.message ?? String(err);
    const payload = {
      error: message,
      statusCode: status,
      response: data,
      tool: name,
    };
    return {
      isError: true,
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
    };
  }
});

function paramExpectsLocationId(spec: GeneratedTool): boolean {
  const schema: any = spec.inputSchema;
  const props = schema?.properties?.params?.properties;
  return !!(props && "locationId" in props);
}

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error(
    `[ghl-mcp-server] ready — ${generatedTools.length} tools available`
  );
}

main().catch((err) => {
  console.error("[ghl-mcp-server] fatal error:", err);
  process.exit(1);
});
